### ISSUE TITLE
Possible Data Inaccuracy's and Confusing UI in Seasonal Stats

### ISSUE THREAD

**Issue by Rinzii** [R6Stats/issues#10]
**Describe the bug**
The seasonal stats tab has a lot of incorrect data (or it's confusing that I may be misunderstanding what the information is presenting)

**Expected behavior**
The data with the bar pictured below seems to not be accurate with the actual seasonal ending rank.
![image](https://user-images.githubusercontent.com/6411222/44556984-6a50ec80-a70a-11e8-8c27-a283bc59c79e.png)

My Current Para Bellum Rank in NA for reference. (i'm also gold 2 in EU)
![image](https://user-images.githubusercontent.com/6411222/44557287-d8e27a00-a70b-11e8-9410-af6eb149d167.png)

I find that the seasonal rank tab is confusing and possibly inaccurate.
![image](https://user-images.githubusercontent.com/6411222/44557488-9bcab780-a70c-11e8-8007-188557ba8272.png)

And this seems to apply to every season in the tab not just parabellum, but its more apparent in the older seasons.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 1c32c539ce0065a41cb79da7bfcd2c71af1afe62-refs/branch-heads/3440@{#794}

**Comment by jengel3** [comment]
This is interesting. I’ll look into this. And yes, the right most rank is the maximum rank you’ve obtained during the season. I’ll add some text to make that clear.

**Comment by Rinzii** [comment]
One thing I should add that I noticed. It seems the ranks are all one rank off of the rank ended on of that season.

![image](https://user-images.githubusercontent.com/6411222/44559846-abe99380-a71a-11e8-98fb-441e816be6b6.png)

For NA I was...
Silver 4 in White Noise
Gold 4 in Chimera
and Gold 3 in Para Bellum as of 8/23/2018

So it seems that all of my ranks in this instance is one rank off. This is of course just for my account, but I'd assume this may likely be applying to all accounts.

**Comment by Rinzii** [comment]
I think I found what is causing it...

Gold 3 is listed as needing 2900 MMR but this is incorrect as 2700 MMR is needed for gold 3

![image](https://user-images.githubusercontent.com/6411222/44560111-ff101600-a71b-11e8-8b3c-5159ba85f054.png)


![image](https://user-images.githubusercontent.com/6411222/44560062-bb1d1100-a71b-11e8-9083-f99fd36fe22d.png)

This breakdown is listed on Ubisoft's site. (Though the data on there site is also riddled with inaccuracies it does have the right MMR points for each rank)

https://game-rainbow6.ubi.com/en-gb/uplay/rewards/season/9

**Comment by jengel3** [comment]
Fantastic. We’re using some data from when we first started the new project
so there’s probably been some changes. I’ll work on it.

**Comment by jengel3** [comment]
Can you confirm that this is fixed?

**Comment by Rinzii** [comment]
Everything looks good now!

![image](https://user-images.githubusercontent.com/6411222/44567721-c125e880-a741-11e8-8fc1-343a61c06b9e.png)
