### ISSUE TITLE
Suggestion for moving of Favorite Players

### ISSUE THREAD

**Issue by Rinzii** [R6Stats/issues#11]
Can we move the favorites tab to the main row of the site instead of burying it under a drop-down in MyAccount?

Since this is going to likely be a very used feature, it would be helpful to have it be quickly accessible.

![image](https://user-images.githubusercontent.com/6411222/44565866-823f6500-a738-11e8-9826-6376d1c2d0dd.png)

**Comment by RayanSaeed** [comment]
+1

**Comment by TynesideGroup** [comment]
Done for the next release 👍
