### ISSUE TITLE
Inconsistencies with leaderboard data

### ISSUE THREAD

**Issue by Rinzii** [R6Stats/issues#12]
**Describe the bug**
The leaderboard has inconsistencies with the data its presenting and the data on individual profiles.

Example:
![image](https://user-images.githubusercontent.com/6411222/44568464-e9631680-a744-11e8-8b8e-b5b4493de2e6.png)

![image](https://user-images.githubusercontent.com/6411222/44568265-0d722800-a744-11e8-8d3f-3003de14b246.png)

![image](https://user-images.githubusercontent.com/6411222/44568289-1ebb3480-a744-11e8-9ea3-c69ac7a458a2.png)

Above is an example, but if those two are incorrect I'd say its safe to say this may be consistent with a lot of accounts on the leaderboard. As I only checked the top 2 players on the leaderboard this does not mean it is ONLY the top two it could be a lot of them or something else may be messing up the sorting.

**Comment by jengel3** [comment]
So, it looks like this is half correct.. 

The leaderboards use `skill - uncertainty` so Beaulu. has the correct score. Pengu _also_ has the correct score, but for the America region, when they're clearly ranked higher in Europe. Looks like the leaderboards are simply overriding the previous value, rather than checking if it's actually greater than the current value. Should be an easy fix.

**Comment by Rinzii** [comment]
I looked around on the leaderboard more and there seems to be some weird stuff.

(THIS IS ALL ON GLOBAL PC)

For example...
![image](https://user-images.githubusercontent.com/6411222/44569772-7a3bf100-a749-11e8-8296-861892c3de0b.png)
I should not be on the leaderboard with this low of a skill rating, especially when you consider the fact that Canadian.EG who has a way higher rating than me is not on the leaderboard. (at least not above me)
![image](https://user-images.githubusercontent.com/6411222/44569855-b8d1ab80-a749-11e8-8a15-e5fab073ba87.png)

There also seems to be a lot of low skilled people who are very high in placement on the leaderboard.
![image](https://user-images.githubusercontent.com/6411222/44569886-d43cb680-a749-11e8-99f1-a200340e6e8c.png)
