### ISSUE TITLE
Couple suggestions

### ISSUE THREAD

**Issue by danielwerg** [R6Stats/issues#14]
Can u swap bomb and hostage? https://i.imgur.com/ZRU5GYY.png
Since bomb most popular and balance game mode.
Also would be cool to have dark theme instead of eyes-bleeding-white.
And no aliases? :(

**Comment by jengel3** [comment]
I agree with the first point, we can do that. 

We're also working on a dark mode, possibly in the release version of the website, otherwise shortly after.

Same as above, aliases are also on our todo list, but I don't have an ETA for those.

Thank you for the feedback! 👍

**Comment by jengel3** [comment]
✔️ Night Mode
✔️ Aliases
✔️ Gamemodes Swapped

Issue: ❌
