### ISSUE TITLE
Make operator in stats header most player operator

### ISSUE THREAD

**Issue by vanucci** [R6Stats/issues#15]
When looking at the operator stats it has been suggested that he operator png thats displayed next your name should be your most played operator. 

Currently its Jaeger 

![jaegerr6stats](https://user-images.githubusercontent.com/10452112/44599682-0512ff00-a7cf-11e8-9902-5e68cf989127.png)

So my most played character is Mute and his png would be displayed instead

suggestion by ChankaNewsNetwork (317710905959907358)

**Comment by danielwerg** [comment]
I think it's should be 1 from def a 1 from atc staying next to each other.
