### ISSUE TITLE
Ela & Zofia have the same stats

### ISSUE THREAD

**Issue by wh0cares** [R6Stats/issues#16]
**Describe the bug**
Ela & Zofia have the same operator stats

**To Reproduce**
1. Go to operators
2. Scroll down to Ela & Zofia stats

**Expected behavior**
Ela & Zofia should not have the same exact stats

**Screenshots**
![capture](https://user-images.githubusercontent.com/1351714/44613857-495ec900-a7e8-11e8-95f1-a988ebaed5da.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Browser [Firefox]
 - Version [61.0.2]

**Additional context**
Bug reported by art.majin on discord

**Comment by TynesideGroup** [comment]
Fixed in the next release 👍
