### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by Mhy278** [R6Stats/issues#21]
Pardon,i think r6stats is the best r6 stats website i have ever seen,but it not support my mother language Chinese. In fact r6stats just provide two languages for users,that's not enough to r6stats. So could you provide the language files that users in other languages can help you to translate it fastly. This is my idea and hope to adopt,thanks.

**Comment by jengel3** [comment]
Hi, we're actually working on this! We will open translations to the community ASAP

**Comment by Mhy278** [comment]
that's great,thanks for your understanding.

**Comment by jengel3** [comment]
Hey @PeterBob, we've opened up translation contributions for the website! You can help out [here](https://www.transifex.com/r6stats/r6stats-website) if you'd like. Please let us know if you'd like us to enable other languages.

Thanks for the help 😄

**Comment by jengel3** [comment]
See #22
