### ISSUE TITLE
Missing German Translations

### ISSUE THREAD

**Issue by KevSlashNull** [R6Stats/issues#28]
**Describe the bug**
There are two missing German translations. They are `stats.titles.seasonal_stats` and `stats.titles.match_stats`.

**To Reproduce**
1. Go to a player statistics page. (e.g. [my page](https://r6stats.com/de/stats/8fa90baa-fc15-4c43-bf37-7bf2240f3e03/))
2. Change the language to **German** (“Deutsch”)
3. Scroll down beyond the “Gesamt KD / WL” box.
4. See missing translations

**Expected behavior**
`stats.titles.seasonal_stats` should be “Saisonstatistiken”.
`stats.titles.match_stats` should be “Matchstatistiken”.

**Screenshots**
![image](https://user-images.githubusercontent.com/28510368/45964934-5d842900-c027-11e8-8b70-60ca7bd5b989.png)

**Desktop (please complete the following information):** independent

**Smartphone (please complete the following information):** independent

**Additional context**
The German language in the language selector should be called “Deutsch” and not “Deutsche”.
`

**Comment by TynesideGroup** [comment]
I have updated the two missing translations, and changed the dropdown selector to say `Deutsch`.

These changes will go live in our next deployment.
