### ISSUE TITLE
Tag Space as Username

### ISSUE THREAD

**Issue by KevSlashNull** [R6Stats/issues#30]
**Describe the bug**
It‘s not a real bug but you can use Tag Space `\xf3\xa0\x80\xa0` ([U+E0020](https://unicode-table.com/en/E0020/)) as username. And I noticed that passwords can be one character long. Also not a bug but not that secure.

**To Reproduce**
Register an account using the Tag Space.

**Expected behavior**
Maybe that it does not work?

**Screenshots**
![image](https://user-images.githubusercontent.com/28510368/46497577-414c6d00-c81b-11e8-9a54-51298b88ed43.png)

**Comment by Mann-o** [comment]
Added validation rules to ensure future passwords are at least 6 characters. Also added a sanisation rule to trim the username before it is validated.
