### ISSUE TITLE
"Daily stats" crashes app

### ISSUE THREAD

**Issue by Jeddunk** [R6Stats/issues#31]
**Describe the bug**
Trying to access "Daily stats", the app crashes and closes down with no warning.

**To Reproduce**
1. (Optional) Logout, skip the login page, enter "Jeddunk" in the username field, choose "PC" in the "Platform" dropdown menu and press "Search"
2. Open the navigation drawer and select "Daily stats"

**Expected behavior**
No crash, access to the "Daily stats" page.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 10 Pro
 - Android Version: Android 9.0 Pie
 - App version: 2.2.0.0

**Additional context**
None

**Comment by wh0cares** [comment]
Thanks for providing the username & platform associated with this issue. I will look into this issue and it should be ready in the next update.

**Comment by Jeddunk** [comment]
You're welcome. I wanted to add that I haven't played a game when I tried to access it, so I suspect that, since there is technically no data, it might cause an error. (Maybe a Null Pointer Exception?)

**Comment by wh0cares** [comment]
I just checked on my device and logs and can't seem to reproduce this crash. Do daily stats still crash on your Mate 10 Pro?

**Comment by wh0cares** [comment]
Crash is fixed in update 2.2.2.0
