### ISSUE TITLE
Search bar stays populated after a search

### ISSUE THREAD

**Issue by vanucci** [R6Stats/issues#6]
When you have searched a user successfully the search bar stays populated even after several page changes, ie blog, leaderboard etc

Not sure if intentional 

win10 
chrome

**Comment by jengel3** [comment]
Looking for input on this one - should this be a feature? It would make it easier for users to access their last searched user. I think we might keep this as a feature until we add some sort of "recently searched" feature.

**Comment by wh0cares** [comment]
I think it should be a feature. It could help a user redo a search if they went to another page or misspelled the username
