### ISSUE TITLE
Visual bug with the seasonal stats tab

### ISSUE THREAD

**Issue by Rinzii** [R6Stats/issues#8]
**Describe the bug**
The seasonal stats section does not correct it's size properly when the browser is not full screen. This creates a visual bug. (This appeared on Google Chrome; Have not tested on other browsers)

**To Reproduce**
1. Resize the browser to anything that's not fullscreen.
2. Expand any season available.
3. The visual bug should appear

**Expected behavior**
The boxes should show all the data and not cut it off halfway.

**Screenshots**
![image](https://user-images.githubusercontent.com/6411222/44556611-86ec2500-a708-11e8-89ac-a15101237164.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 1c32c539ce0065a41cb79da7bfcd2c71af1afe62-refs/branch-heads/3440@{#794}

**Comment by jengel3** [comment]
Deployed a hacky fix for this. Should be resolved for now, but I want to look into a better way to support animating this.
